CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS tedtalks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    "date" DATE NOT NULL,
    views INTEGER NOT NULL,
    likes INTEGER NOT NULL,
    link VARCHAR(255) NOT NULL
);