spring:
  application:
    name: tedtalks
  datasource:
    url: jdbc:postgresql://localhost:5432/tedtalks
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect